
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: medilabo
    volumes:
      - ./infrastructure/mysql:/docker-entrypoint-initdb.d
    networks:
      - microservices-network

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./infrastructure/mongo:/docker-entrypoint-initdb.d
    networks:
      - microservices-network

  microservice1:
    container_name: patient
    build:
      context: PatientMicroservice
      dockerfile: Dockerfile-microservice1
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medilabo?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    depends_on:
      - mysql
    networks:
      - microservices-network

  microservice2:
    container_name: doctors_notes
    build:
      # Context is the directory where the Dockerfile is located
      # Thus, we can access it without any path.
      context: DoctorsNotesMicroservice
      dockerfile: Dockerfile-microservice2
    ports:
      - "8081:8081"
    environment:
      # Override the location of the mongo database
      SPRING_DATA_MONGODB_HOST: mongo
    depends_on:
      - mongo
    networks:
      - microservices-network

  microservice3:
    container_name: reports_gateway
    build:
      context: ReportsGatewayMicroservice
      dockerfile: Dockerfile-microservice3
    environment:
      FEIGNPATIENT_URL: microservice1:8080
      FEIGNDOCTORS_NOTES_URL: microservice2:8081
    ports:
      - "8082:8082"
    networks:
      - microservices-network
    depends_on:
      - microservice1
      - microservice2
networks:
  microservices-network:
    driver: bridge
